[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "DeviceLibrary/_version.py"

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}

[project]
name = "robotframework-devicelibrary"
description = "Robot Framework library for interfacing with Devices"
requires-python = ">=3.7"
keywords = ["testing"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "readme"]
dependencies = [
  "robotframework >= 6.0.0, < 7.0.0",
  "unidecode >= 1.3.6, < 2.0.0",
  "device-test-core @ git+https://github.com/reubenmiller/device-test-core.git@0.10.0#egg=device-test-core",
]

[project.optional-dependencies]
all = [
    "robotframework-devicelibrary[ssh]",
    "robotframework-devicelibrary[docker]",
    "robotframework-devicelibrary[local]",
]
ssh = [
    "device-test-core[ssh] @ git+https://github.com/reubenmiller/device-test-core.git@0.10.0#egg=device-test-core",
]
local = [
    "device-test-core[local] @ git+https://github.com/reubenmiller/device-test-core.git@0.10.0#egg=device-test-core",
]
docker = [
    "device-test-core[docker] @ git+https://github.com/reubenmiller/device-test-core.git@0.10.0#egg=device-test-core",
]

test = [
    "pytest >= 7.2.0, < 8.0.0",
]
